// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", undefined, "Hello from ReScript and React");
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
